import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/navbar/Navbar';
import HomeD from '../components/home/Home';

const Home: NextPage = () => {
  return (
   <>
     <Head>
        <title>Nahmii | Bond </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.svg" />
      </Head>
    <Navbar />
    <HomeD />
   </>
  );
}
export default Home
